name: benchsbi
channels:
  - pytorch
  - conda-forge
dependencies:
  - cpuonly=2.0
  - ipython=8.12.0
  - numpy=1.25.0
  - pip=23.1.2
  - python=3.9.16
  - pytorch=1.13.1
  - pip:
      - benchopt==1.4.0
      - lampe==0.8.0
      - POT==0.9.0
      - pyro-ppl==1.8.4
      - pytest==7.4.0
      - sbi==0.21.0
      - sbibm==1.0.8
      - zuko==0.2.1
